force-app/main/default/objects/adjustment__c/adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <label>adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/adjustment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/adjustment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>IN_PROGRESS</fullName>
                <label>In progress</label>
            </value>
            <value>
                <fullName>PENDING_ACCEPTED</fullName>
                <label>Pending accepted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Adjusment_Service.cls
public with sharing class Adjusment_Service {
    public static final string PENDING_ACCEPTED = 'PENDING_ACCEPTED';

    public static Adjustment__c createAdjustment(Integer amount, String status, String caseId, String externalId){
        Adjustment__c adj = new Adjustment__c();
        adj.Name = 'Adjustment';
        adj.Amount__c = amount;
        adj.Status__c = status;
        adj.Case__c = caseId;
        adj.External_Id__c = externalId;
        insert adj;
        return adj;
    }

    public static void afterUpdate(Map<Id, Adjustment__c> newMap, Map<Id, Adjustment__c> oldMap){
            if(newMap.values().get(0).Amount__c > 1000 && PENDING_ACCEPTED.equals(newMap.values().get(0).Status__c) && !PENDING_ACCEPTED.equals(oldMap.values().get(0).Status__c)){
                WS_TransacionAPI_Token.changeStatus(newMap.values().get(0).External_Id__c, newMap.values().get(0).Status__c, newMap.values().get(0).Id);
            }
    }
}